//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeytinyağı_otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depo_Tablo
    {
        public string İd { get; set; }
        public Nullable<double> GemlikZeytin { get; set; }
        public Nullable<double> DomatZeytin { get; set; }
        public Nullable<double> EsekZeytin { get; set; }
        public Nullable<double> AyvalilZeytin { get; set; }
        public Nullable<double> ZeytinYagi { get; set; }
    }
}
