//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeytinyağı_otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kasa_Tablo
    {
        public string SiparisNo { get; set; }
        public Nullable<double> SatisFiyati { get; set; }
        public Nullable<double> AlinanPara { get; set; }
        public Nullable<double> ToplamPara { get; set; }
    }
}
