//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeytinyağı_otomasyon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZeytinEntities : DbContext
    {
        public ZeytinEntities()
            : base("name=ZeytinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Depo_Tablo> Depo_Tablo { get; set; }
        public virtual DbSet<Kasa_Tablo> Kasa_Tablo { get; set; }
        public virtual DbSet<Musteri_Tablo> Musteri_Tablo { get; set; }
        public virtual DbSet<Siparis_Tablo> Siparis_Tablo { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Urun_Tablo> Urun_Tablo { get; set; }
    }
}
