//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeytinyağı_otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri_Tablo
    {
        public double UrunBarkod { get; set; }
        public Nullable<int> Musteriİd { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<double> TelefonNumarasi { get; set; }
        public string Adres { get; set; }
        public string ZeytinTuru { get; set; }
        public Nullable<double> Miktar { get; set; }
        public Nullable<double> Fiyat { get; set; }
    }
}
